name: Coverage

on:
  push:
    branches:
      - master
  pull_request_target:
    branches:
      - "*"
jobs:
  coverage:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "12.22.1"

      - name: Setup SSH to install dependencies
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # - name: Install dependencies
      #   run: npm ci

      # - name: Run Sol Coverage
      #   run: npm run coverage

      # - name: Publish to Codecov.io
      #   run: bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}
