name: Publish
on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: npm-publish
    runs-on: ubuntu-18.04
    steps:
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v2.x
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "12.22.1"

      - run: npm ci
      - run: npm run compile
      - run: npm test

      - name: Publish to NPM
        uses: JS-DevTools/npm-publish@v1
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          token: ${{ secrets.NPM_ACCESS_TOKEN }}
          access: "public"
